openapi: 3.0.0
info: 
  title: Dribble API
  description: Showcasing 3 API endpoints from the Dribble API
  version: 1.0.0
  
 
paths: 
  /user/shots:
    get: 
      summary: List the users's shots
      description: List the design shots of the authenticated user
      responses: 
        default: 
          description: $100
          
      
    post:
      summary: Generates an invoice based on provided instructions.
      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              type: object
              required:
                - instruction
              properties:
                instruction: 
                  type: string
                  example: Create an invoice from Jane Doe to Chimoney Incorporated for Web Dev Service which I provided for 4 months at $5/month and for Project Management cost of $100 with tax rate of 5%.
            
      responses: 
        '200': 
          description: Success
          content: 
            application/json: 
              schema:
                type: object
                properties:
                  status: 
                    type: string
                    example: Successful invoice generation
                  data:
                    type: object
                    properties: 
                      invoiceNumber:
                        type: string
                        example: invoice_2025_123_web_project
                      invoiceDate: 
                        type: string
                        format: date
                        example: 2025-08-24
                      sender: 
                         type: object
                         properties: 
                          firstName: 
                            type: string
                            example: John
                          lastName: 
                            type: string
                            example: Doe
                      recipient:
                         type: object
                         properties: 
                          companyName:
                            type: string
                            example: Chimoney Incorporated
                          addressLine1: 
                            type: string
                            example: Web Dev Service
                          email:
                            type: string
                            example: chimoneyapi@gmail.com
                              
        '400':